// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADFq6v7oq_7XOIjTqUCnW9i0gsHLQFF0c',
    appId: '1:580203880699:web:9edbe7b3b23b3d2834105e',
    messagingSenderId: '580203880699',
    projectId: 'myparade-c6c30',
    authDomain: 'myparade-c6c30.firebaseapp.com',
    storageBucket: 'myparade-c6c30.firebasestorage.app',
    measurementId: 'G-G19YHRP50D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS8c9A5L6OsuPq1QROia8l3p16k_52WOg',
    appId: '1:580203880699:android:b1534cbeb59edba234105e',
    messagingSenderId: '580203880699',
    projectId: 'myparade-c6c30',
    storageBucket: 'myparade-c6c30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL4wIBRtFOUPIZIvbgIpGZqRDXy54gTHM',
    appId: '1:580203880699:ios:0b7122a4f06c555234105e',
    messagingSenderId: '580203880699',
    projectId: 'myparade-c6c30',
    storageBucket: 'myparade-c6c30.firebasestorage.app',
    iosBundleId: 'com.example.myparadefixed',
  );
}
